import mongoose, { Schema } from "mongoose";

const complainSchema=new Schema({
    name:{
        type:String,
        require:true,
    },
    fatcherName:{
        type:String,
        require:true,
    },
    age:{
        type:Number,
        require:true,
    },
    contactAddress:{
        type:String,
        require:true,
    },
    missingSince:{
        type:Date,
        require:true,
    },
    nearPoliceStationName:{
        type:String,
        require:true,
    },
    Nationality:{
        type:String,
        require:true,
    },
    gender:{
        type:String,
        require:true,
    },
    missingFrom:{
        type:String,
        require:true,
    },
    images:[
        {
            type:String,
        }
    ],
    languageKnown:{
        type:String,
        require:true,
    },
    habitsAddicationsHobbies:{
         type:String,
       
    },
    isStudent:{
         type:String,
        require:true,
    },
    schoolName:{
         type:String,
     
    },
    collegeName:{
         type:String,
        
    },
    placeOfRegularVisit:{
         type:String,
     
    },
    contactNumber:{
        type:Number,
        require:true,
    },
    height:{
         type:String,
        require:true,
    },
    hairColor:{
         type:String,
      
    },
    built:{
         type:String,
        require:true,
    },
    face:{
         type:String,
        require:true,
    },
    identificationMarks:{
         type:String,
        require:true,
    },
    health:{
         type:String,
        require:true,
    },
    maentalHealth:{
         type:String,
        require:true,
    },
    reportFill:{
        type:Boolean,
        default:false,
    },
    reportNo:{
         type:String,    
    },
    stationName:{
        type:String,  
   },
   dateAndTime:{
    type:Date,  
    },
    gdeNo:{
        type:String,  
   },
   lastSeenwithWhomeAndbyWhome:{
    type:String,  
    },
    apparentCauseofLeaving:{
        type:String,  
   },
   dreesatTimeOfLeaving:{
    type:String,  
    },
    month:{
        type:String,  
    },
    year:{
        type:Number,
    },
    email:{
        type:String,
    },
})

const Complain=mongoose.model("Complaints",complainSchema)

export default Complain;